import AppKit
import DictationCore
import XCTest

/// Проверка настоящей записи в буфер обмена.
///
/// Работаем на своей именованной доске, а не на общей: тест не имеет права
/// затирать то, что человек в этот момент скопировал.
final class HostOnlyPasteboardTests: XCTestCase {
    private var boardName: String!
    private var board: NSPasteboard!
    private var pasteboard: HostOnlyPasteboard!

    override func setUp() {
        boardName = "is.waiwai.dictation.tests.\(UUID().uuidString)"
        board = NSPasteboard(name: NSPasteboard.Name(boardName))
        pasteboard = HostOnlyPasteboard(name: boardName)
    }

    override func tearDown() {
        board.releaseGlobally()
    }

    func testТекстПопадаетВБуфер() throws {
        try pasteboard.writeHostOnly("привет из диктовки")

        XCTAssertEqual(board.string(forType: .string), "привет из диктовки")
    }

    /// Пометки для менеджеров буфера обмена.
    ///
    /// Это соглашение nspasteboard.org: с ними сторонние менеджеры не кладут
    /// запись в свою историю. Без них продиктованное — включая пароли, номера и
    /// всё прочее, что человек надиктовал, — оседает в чужой базе навсегда.
    func testЗаписьПомеченаКакНеСохраняемая() throws {
        try pasteboard.writeHostOnly("секрет")

        let types = try XCTUnwrap(board.pasteboardItems?.first?.types)
        XCTAssertTrue(types.contains(HostOnlyPasteboard.transientType), "нет TransientType")
        XCTAssertTrue(types.contains(HostOnlyPasteboard.concealedType), "нет ConcealedType")
        XCTAssertTrue(types.contains(HostOnlyPasteboard.autoGeneratedType), "нет AutoGeneratedType")
    }

    func testПовторнаяЗаписьНеОставляетПрошлогоТекста() throws {
        try pasteboard.writeHostOnly("первый")
        try pasteboard.writeHostOnly("второй")

        XCTAssertEqual(board.pasteboardItems?.count, 1)
        XCTAssertEqual(board.string(forType: .string), "второй")
    }

    func testКаждаяЗаписьМеняетСчётчикИзменений() throws {
        let before = board.changeCount
        try pasteboard.writeHostOnly("текст")

        // Счётчик — то, по чему приложения понимают, что содержимое новое.
        XCTAssertGreaterThan(board.changeCount, before)
    }

    func testОбщийБуферНеТрогается() throws {
        let generalBefore = NSPasteboard.general.changeCount

        try pasteboard.writeHostOnly("текст")

        XCTAssertEqual(NSPasteboard.general.changeCount, generalBefore)
    }
}
