import AppKit
import DictationCore
import XCTest

/// Проверка настоящей записи в буфер обмена.
///
/// Работаем на своей именованной доске, а не на общей: тест не имеет права
/// затирать то, что человек в этот момент скопировал.
final class HostOnlyPasteboardTests: XCTestCase {
    private var boardName: String!
    private var board: NSPasteboard!
    private var pasteboard: HostOnlyPasteboard!

    override func setUp() {
        boardName = "is.waiwai.dictation.tests.\(UUID().uuidString)"
        board = NSPasteboard(name: NSPasteboard.Name(boardName))
        pasteboard = HostOnlyPasteboard(name: boardName)
    }

    override func tearDown() {
        board.releaseGlobally()
    }

    func testТекстПопадаетВБуфер() throws {
        _ = try pasteboard.beginHostOnlyWrite("привет из диктовки")

        XCTAssertEqual(board.string(forType: .string), "привет из диктовки")
    }

    /// Пометки для менеджеров буфера обмена.
    ///
    /// Это соглашение nspasteboard.org: с ними сторонние менеджеры не кладут
    /// запись в свою историю. Без них продиктованное — включая пароли, номера и
    /// всё прочее, что человек надиктовал, — оседает в чужой базе навсегда.
    func testЗаписьПомеченаКакНеСохраняемая() throws {
        _ = try pasteboard.beginHostOnlyWrite("секрет")

        let types = try XCTUnwrap(board.pasteboardItems?.first?.types)
        XCTAssertTrue(types.contains(HostOnlyPasteboard.transientType), "нет TransientType")
        XCTAssertTrue(types.contains(HostOnlyPasteboard.concealedType), "нет ConcealedType")
        XCTAssertTrue(types.contains(HostOnlyPasteboard.autoGeneratedType), "нет AutoGeneratedType")
    }

    func testConcealedЗаписьНеПерезаписываетсяПовторно() throws {
        _ = try pasteboard.beginHostOnlyWrite("первый")

        XCTAssertThrowsError(try pasteboard.beginHostOnlyWrite("второй")) { error in
            XCTAssertEqual(error as? TextInsertionError, .protectedClipboard)
        }
        XCTAssertEqual(board.string(forType: .string), "первый")
    }

    func testКаждаяЗаписьМеняетСчётчикИзменений() throws {
        let before = board.changeCount
        _ = try pasteboard.beginHostOnlyWrite("текст")

        // Счётчик — то, по чему приложения понимают, что содержимое новое.
        XCTAssertGreaterThan(board.changeCount, before)
    }

    func testОбщийБуферНеТрогается() throws {
        let generalBefore = NSPasteboard.general.changeCount

        _ = try pasteboard.beginHostOnlyWrite("текст")

        XCTAssertEqual(NSPasteboard.general.changeCount, generalBefore)
    }

    func testДопустимыйSnapshotВосстанавливается() throws {
        board.prepareForNewContents(with: .currentHostOnly)
        let item = NSPasteboardItem()
        item.setString("до диктовки", forType: .string)
        XCTAssertTrue(board.writeObjects([item]))

        let transaction = try pasteboard.beginHostOnlyWrite("диктовка")
        XCTAssertEqual(board.string(forType: .string), "диктовка")
        try pasteboard.restore(transaction)

        XCTAssertEqual(board.string(forType: .string), "до диктовки")
    }

    func testЧужоеИзменениеClipboardНеПерезаписывается() throws {
        board.prepareForNewContents(with: .currentHostOnly)
        board.setString("до", forType: .string)
        let transaction = try pasteboard.beginHostOnlyWrite("диктовка")
        board.prepareForNewContents(with: .currentHostOnly)
        board.setString("новое пользователя", forType: .string)

        try pasteboard.restore(transaction)

        XCTAssertEqual(board.string(forType: .string), "новое пользователя")
    }

    /// Privacy budget стирает snapshot через две секунды. Если к этому моменту
    /// clipboard всё ещё наш, прежнее содержимое человека потеряно навсегда —
    /// молчать об этом нельзя, а диктовка не должна оставаться лежать в буфере.
    func testПросроченныйSnapshotПриНашемВладенииНеМолчит() throws {
        board.prepareForNewContents(with: .currentHostOnly)
        board.setString("до диктовки", forType: .string)
        let quick = HostOnlyPasteboard(name: boardName, snapshotLifetime: 0.05)
        let transaction = try quick.beginHostOnlyWrite("диктовка")

        Thread.sleep(forTimeInterval: 0.3)

        XCTAssertThrowsError(try quick.restore(transaction)) { error in
            XCTAssertEqual(error as? TextInsertionError, .clipboardRestoreFailed)
        }
        XCTAssertNil(
            board.string(forType: .string),
            "Продиктованное не имеет права лежать в clipboard после провала restore"
        )
    }

    /// Тот же просроченный snapshot, но человек уже скопировал своё: восстановить
    /// нечего, чужую запись трогать нельзя, и это не ошибка.
    func testПросроченныйSnapshotПослеЧужойЗаписиМолчит() throws {
        let quick = HostOnlyPasteboard(name: boardName, snapshotLifetime: 0.05)
        let transaction = try quick.beginHostOnlyWrite("диктовка")

        Thread.sleep(forTimeInterval: 0.3)
        board.prepareForNewContents(with: .currentHostOnly)
        board.setString("новое пользователя", forType: .string)

        XCTAssertNoThrow(try quick.restore(transaction))
        XCTAssertEqual(board.string(forType: .string), "новое пользователя")
    }

    func testНеподдерживаемыйТипЗащищаетClipboardДоMutation() throws {
        let custom = NSPasteboard.PasteboardType("com.example.secret")
        board.prepareForNewContents(with: .currentHostOnly)
        board.setData(Data([1, 2, 3]), forType: custom)
        let before = board.changeCount

        XCTAssertThrowsError(try pasteboard.beginHostOnlyWrite("диктовка")) { error in
            XCTAssertEqual(error as? TextInsertionError, .protectedClipboard)
        }
        XCTAssertEqual(board.changeCount, before)
        XCTAssertEqual(board.data(forType: custom), Data([1, 2, 3]))
    }

    func testОшибкаЗаписиВозвращаетПрежнийClipboard() throws {
        board.prepareForNewContents(with: .currentHostOnly)
        board.setString("до диктовки", forType: .string)
        let writer = FailFirstPasteboardWriter()
        let failingPasteboard = HostOnlyPasteboard(
            name: boardName,
            writeObjects: writer.write
        )

        XCTAssertThrowsError(try failingPasteboard.beginHostOnlyWrite("диктовка")) { error in
            XCTAssertEqual(error as? TextInsertionError, .clipboardWriteFailed)
        }
        XCTAssertEqual(board.string(forType: .string), "до диктовки")
    }
}

private final class FailFirstPasteboardWriter: @unchecked Sendable {
    private let lock = NSLock()
    private var callCount = 0

    func write(_ board: NSPasteboard, _ objects: [NSPasteboardWriting]) -> Bool {
        lock.lock()
        callCount += 1
        let shouldFail = callCount == 1
        lock.unlock()
        return shouldFail ? false : board.writeObjects(objects)
    }
}
