import AppKit
import Carbon.HIToolbox
import DictationCore
import Foundation

// MARK: - Clipboard

/// Write the dictated text to the clipboard.
public protocol DictationPasteboard: Sendable {
    /// Keep valid previous contents in memory and put local text.
    func beginHostOnlyWrite(_ text: String) throws -> PasteboardTransaction
    /// Return the original content only if the post still belongs to us.
    func restore(_ transaction: PasteboardTransaction) throws
}

public struct PasteboardTransaction: Sendable, Equatable {
    fileprivate let id: UUID

    init(id: UUID = UUID()) {
        self.id = id
    }
}

private final class PasteboardTransactionStorage: @unchecked Sendable {
    struct Snapshot {
        let items: [[NSPasteboard.PasteboardType: Data]]
        let ownedChangeCount: Int
    }

    /// What is left of the transaction at the time of restore.
    enum Claim {
        /// Snapshot is still in memory - restoration is possible.
        case snapshot(Snapshot)
        /// Privacy budget has already erased the contents; All that remains is the ownership counter.
        /// According to it, restore distinguishes “a person has already copied his own” from “previous
        /// contents are lost forever."
        case expired(ownedChangeCount: Int)
        /// There was no transaction or it has already been restored.
        case missing
    }

    private let lock = NSLock()
    private var snapshots: [UUID: Snapshot] = [:]
    /// Tombstone expired snapshot. There is no content here - only Int,
    /// therefore the privacy budget is not violated.
    private var expiredOwnership: [UUID: Int] = [:]
    private let lifetime: TimeInterval

    init(lifetime: TimeInterval) {
        self.lifetime = lifetime
    }

    func insert(_ snapshot: Snapshot, for id: UUID) {
        lock.lock()
        // Insertions come strictly one at a time: the old tombstone is no longer available
        // present, and the dictionary does not grow indefinitely.
        expiredOwnership.removeAll()
        snapshots[id] = snapshot
        lock.unlock()

        // Even if the calling task died between write and restore,
        // sensitive snapshot does not survive the privacy budget. Three seconds:
        // seconds to consume ⌘V by a slow application (VoiceInk #722),
        // up to half a second to release modifiers and reserve for the scheduler.
        DispatchQueue.global(qos: .utility).asyncAfter(deadline: .now() + lifetime) { [weak self] in
            self?.expire(id)
        }
    }

    func take(_ id: UUID) -> Claim {
        lock.lock()
        defer { lock.unlock() }
        if let snapshot = snapshots.removeValue(forKey: id) {
            return .snapshot(snapshot)
        }
        if let owned = expiredOwnership.removeValue(forKey: id) {
            return .expired(ownedChangeCount: owned)
        }
        return .missing
    }

    private func expire(_ id: UUID) {
        lock.lock()
        if let snapshot = snapshots.removeValue(forKey: id) {
            expiredOwnership[id] = snapshot.ownedChangeCount
        }
        lock.unlock()
    }
}

/// A clipboard limited to this computer.
///
/// A regular recording sends the content to the Universal Clipboard, and the dictated
/// the text appears on all Apple ID devices via iCloud - directly contrary to
/// product promise. `prepareForNewContents(with: .currentHostOnly)` is
/// disables, and marks ask buffer managers not to save the entry to history.
///
/// Naked `clearContents()` is prohibited here, and this is checked separately -
/// `scripts/check-network-surface.sh`.
public struct HostOnlyPasteboard: DictationPasteboard {
    /// The convention of third-party clipboard managers is “do not save.”
    static let transientType = NSPasteboard.PasteboardType("org.nspasteboard.TransientType")
    static let concealedType = NSPasteboard.PasteboardType("org.nspasteboard.ConcealedType")
    static let autoGeneratedType = NSPasteboard.PasteboardType("org.nspasteboard.AutoGeneratedType")

    /// Board name. In the appendix - general; in the test its own, so that the run does not overwrite
    /// what the person copied at that moment.
    private let name: String
    private let writeObjects: @Sendable (NSPasteboard, [NSPasteboardWriting]) -> Bool
    private let transactions: PasteboardTransactionStorage

    public init(name: String = NSPasteboard.Name.general.rawValue) {
        self.init(name: name, snapshotLifetime: 3) { pasteboard, objects in
            pasteboard.writeObjects(objects)
        }
    }

    init(
        name: String,
        snapshotLifetime: TimeInterval = 3,
        writeObjects: @escaping @Sendable (NSPasteboard, [NSPasteboardWriting]) -> Bool = {
            pasteboard, objects in
            pasteboard.writeObjects(objects)
        }
    ) {
        self.name = name
        self.writeObjects = writeObjects
        self.transactions = PasteboardTransactionStorage(lifetime: snapshotLifetime)
    }

    public func beginHostOnlyWrite(_ text: String) throws -> PasteboardTransaction {
        let pasteboard = NSPasteboard(name: NSPasteboard.Name(name))
        let snapshot = materializeSnapshot(from: pasteboard)
        pasteboard.prepareForNewContents(with: .currentHostOnly)
        let ownedChangeCount = pasteboard.changeCount
        guard writeObjects(pasteboard, [dictatedItem(text)]) else {
            do {
                try restoreSnapshot(snapshot, to: pasteboard, ownedChangeCount: ownedChangeCount)
            } catch {
                throw TextInsertionError.clipboardRestoreFailed
            }
            throw TextInsertionError.clipboardWriteFailed
        }

        let transaction = PasteboardTransaction()
        transactions.insert(
            .init(items: snapshot, ownedChangeCount: pasteboard.changeCount),
            for: transaction.id
        )
        return transaction
    }

    /// Explicit Copy command: the user himself allowed to replace the clipboard, but
    /// The dictation should still not go to Universal Clipboard or history.
    public func copyHostOnly(_ text: String) throws {
        try write(text, to: NSPasteboard(name: NSPasteboard.Name(name)))
    }

    public func restore(_ transaction: PasteboardTransaction) throws {
        let pasteboard = NSPasteboard(name: NSPasteboard.Name(name))
        // `take` simultaneously clears the sensitive snapshot from memory - even
        // when ownership is already lost and nothing can be restored.
        switch transactions.take(transaction.id) {
        case let .snapshot(snapshot):
            try restoreSnapshot(
                snapshot.items,
                to: pasteboard,
                ownedChangeCount: snapshot.ownedChangeCount
            )
        case let .expired(ownedChangeCount):
            // Privacy budget has already erased the person's previous content. If a person
            // I have since copied mine - there is nothing to restore and this is not an error.
            guard pasteboard.changeCount == ownedChangeCount else { return }
            // Clipboard is still ours: it contains dictation. You can't leave her
            // and “success” here would be a silent loss of the person’s contents.
            pasteboard.prepareForNewContents(with: .currentHostOnly)
            throw TextInsertionError.clipboardRestoreFailed
        case .missing:
            return
        }
    }

    private func materializeSnapshot(
        from pasteboard: NSPasteboard
    ) -> [[NSPasteboard.PasteboardType: Data]] {
        var result: [[NSPasteboard.PasteboardType: Data]] = []

        for item in pasteboard.pasteboardItems ?? [] {
            var values: [NSPasteboard.PasteboardType: Data] = [:]
            for type in item.types {
                // Clipboard metadata such as ConcealedType is data like any other type.
                // It must never block dictation. Lazy file promises may not materialize
                // outside a drag session; preserve every representation that is available.
                if let data = item.data(forType: type) { values[type] = data }
            }
            if !values.isEmpty { result.append(values) }
        }
        return result
    }

    private func write(_ text: String, to pasteboard: NSPasteboard) throws {
        pasteboard.prepareForNewContents(with: .currentHostOnly)
        guard writeObjects(pasteboard, [dictatedItem(text)]) else {
            throw TextInsertionError.clipboardWriteFailed
        }
    }

    private func dictatedItem(_ text: String) -> NSPasteboardItem {
        let item = NSPasteboardItem()
        item.setString(text, forType: .string)
        item.setString("", forType: Self.transientType)
        item.setString("", forType: Self.concealedType)
        item.setString("", forType: Self.autoGeneratedType)
        return item
    }

    private func restoreSnapshot(
        _ snapshot: [[NSPasteboard.PasteboardType: Data]],
        to pasteboard: NSPasteboard,
        ownedChangeCount: Int
    ) throws {
        guard pasteboard.changeCount == ownedChangeCount else { return }
        pasteboard.prepareForNewContents(with: .currentHostOnly)
        guard !snapshot.isEmpty else { return }
        let restored = snapshot.map { values -> NSPasteboardItem in
            let item = NSPasteboardItem()
            for (type, data) in values { item.setData(data, forType: type) }
            return item
        }
        guard writeObjects(pasteboard, restored) else {
            throw TextInsertionError.clipboardWriteFailed
        }
    }
}

// MARK: - System edges

/// Everything that the insert asks the system and does with it.
///
/// Behind the protocol - because the real answers depend on what the person
/// doing at the computer right now: is the password field open, what keys
/// clamped, whether the application is alive, where we are aiming.
public protocol InputSystem: Sendable {
    /// Secure input: password field, terminal with keyboard protection, manager
    /// passwords. The system prohibits both sending events and reading the keyboard there.
    var isSecureInputEnabled: Bool { get }
    var isAccessibilityTrusted: Bool { get }
    func frontmostApplication() -> TargetApplication?
    /// Which modifiers are clamped right now.
    func heldModifiers() -> CGEventFlags
    /// Return focus to the application. `false` - the application no longer exists.
    func activate(_ target: TargetApplication) async -> Bool
    func post(keyCode: CGKeyCode, flags: CGEventFlags) throws
}

public struct SystemInput: InputSystem {
    public init() {}

    public var isSecureInputEnabled: Bool { IsSecureEventInputEnabled() }
    public var isAccessibilityTrusted: Bool { AXIsProcessTrusted() }

    public func frontmostApplication() -> TargetApplication? {
        guard let app = NSWorkspace.shared.frontmostApplication else { return nil }
        return TargetApplication(
            bundleIdentifier: app.bundleIdentifier,
            processIdentifier: app.processIdentifier,
            localizedName: app.localizedName
        )
    }

    public func heldModifiers() -> CGEventFlags {
        CGEventSource.flagsState(.combinedSessionState)
    }

    public func activate(_ target: TargetApplication) async -> Bool {
        guard let app = NSRunningApplication(processIdentifier: target.processIdentifier) else {
            return false
        }
        guard !app.isActive else { return true }

        app.activate()
        // A short pause: switching focus is not instantaneous, but pressing,
        // sent ahead of time will go to the wrong place.
        do {
            try await Task.sleep(for: .milliseconds(120))
        } catch {
            return false
        }
        return true
    }

    public func post(keyCode: CGKeyCode, flags: CGEventFlags) throws {
        guard let source = CGEventSource(stateID: .combinedSessionState),
              let keyDown = CGEvent(keyboardEventSource: source, virtualKey: keyCode, keyDown: true),
              let keyUp = CGEvent(keyboardEventSource: source, virtualKey: keyCode, keyDown: false)
        else {
            throw TextInsertionError.targetUnavailable
        }

        keyDown.flags = flags
        keyUp.flags = flags
        keyDown.post(tap: .cgSessionEventTap)
        keyUp.post(tap: .cgSessionEventTap)
    }
}

// MARK: - Insert

/// Insert recognized text into the active application.
///
/// Works via the clipboard and synthetic pressing ⌘V: this is the only one
/// a way to insert text into an arbitrary application without knowing its device.
public struct TextInserter: TextInserting {
    /// Modifiers, the release of which we wait for before ⌘V.
    ///
    /// Otherwise, ⌘V will mix with the held modifier and turn into someone else's
    /// combination - for example, in Fn+⌘V, which the application will understand completely differently.
    ///
    /// Fn is required in the list: it is a hotkey available in the settings, and
    /// without it, the wait would end while the key is still held.
    public static let watchedModifiers: CGEventFlags = [
        .maskCommand, .maskControl, .maskAlternate, .maskShift, .maskSecondaryFn,
    ]

    /// How long to wait for release and in what steps.
    static let releasePollLimit = 50
    static let releasePollInterval = Duration.milliseconds(10)
    private let system: any InputSystem
    private let pasteboard: any DictationPasteboard
    private let restoreDelay: Duration

    public init(
        system: any InputSystem = SystemInput(),
        pasteboard: any DictationPasteboard = HostOnlyPasteboard(),
        restoreDelay: Duration = .milliseconds(1000)
    ) {
        self.system = system
        self.pasteboard = pasteboard
        self.restoreDelay = restoreDelay
    }

    public func frontmostApplication() -> TargetApplication? {
        system.frontmostApplication()
    }

    /// A wrapper over a single implementation.
    ///
    /// There is exactly one body. The two bodies would separate, and the speed display would show
    /// the path that the product does not take.
    public func insert(_ text: String, into target: TargetApplication?) async throws {
        _ = try await insertReportingMarks(text, into: target)
    }

    public func insertReportingMarks(
        _ text: String,
        into target: TargetApplication?
    ) async throws -> InsertionMarks {
        guard !text.isEmpty else { return InsertionMarks() }
        guard let target else { throw TextInsertionError.targetUnavailable }

        // Protected input is not a failure, but a normal situation.
        guard !system.isSecureInputEnabled else {
            throw TextInsertionError.secureInputActive
        }
        guard system.isAccessibilityTrusted else {
            throw TextInsertionError.accessibilityPermissionDenied
        }

        // Return focus BEFORE writing to the buffer. If the application is no longer available, continue
        // you can’t go, and the buffer has not yet been touched at this moment: otherwise the person
        // would lose what was copied where the pasting did not take place anyway.
        try await activate(target)
        try validateTarget(target)
        try validateProtectedState()

        let transaction = try pasteboard.beginHostOnlyWrite(text)
        let pasteDispatchedAt: ContinuousClock.Instant
        do {
            try await waitForModifiersRelease()
            // The last check is performed after changing the clipboard and directly
            // before an irreversible event Cmd+V.
            try validateTarget(target)
            try validateProtectedState()
            try system.post(keyCode: CGKeyCode(kVK_ANSI_V), flags: .maskCommand)
            // Header: from now on, the text is in someone else's window.
            // Everything further is buffer protection, and it is not speed.
            pasteDispatchedAt = .now
        } catch {
            do {
                try pasteboard.restore(transaction)
            } catch {
                throw TextInsertionError.clipboardRestoreFailed
            }
            throw error
        }

        // Slow apps may consume the pasteboard from a later event-loop turn. Keep the
        // dictated text available for one second, but do not keep the UI in an
        // “Inserting” state after Cmd+V has already been dispatched.
        if restoreDelay == .zero {
            do {
                try pasteboard.restore(transaction)
            } catch {
                throw TextInsertionError.insertedButClipboardRestoreFailed
            }
            return InsertionMarks(
                pasteDispatchedAt: pasteDispatchedAt,
                clipboardRestoredAt: .now
            )
        }

        let pasteboard = self.pasteboard
        let restoreDelay = self.restoreDelay
        Task.detached(priority: .utility) {
            try? await Task.sleep(for: restoreDelay)
            try? pasteboard.restore(transaction)
        }
        return InsertionMarks(pasteDispatchedAt: pasteDispatchedAt)
    }

    public func pressReturn() async throws {
        guard !system.isSecureInputEnabled else {
            throw TextInsertionError.secureInputActive
        }
        guard system.isAccessibilityTrusted else {
            throw TextInsertionError.accessibilityPermissionDenied
        }
        try system.post(keyCode: CGKeyCode(kVK_Return), flags: [])
    }

    /// Return focus to the application where the dictation began.
    ///
    /// The application could be closed while recognition was in progress. Insert "somewhere"
    /// in this case it is impossible: there is now an arbitrary window ahead - up to someone else's
    /// password fields, and what was dictated would go there.
    private func activate(_ target: TargetApplication) async throws {
        guard await system.activate(target) else {
            throw TextInsertionError.targetUnavailable
        }
    }

    private func validateTarget(_ target: TargetApplication) throws {
        guard system.frontmostApplication()?.processIdentifier == target.processIdentifier else {
            throw TextInsertionError.targetChanged
        }
    }

    private func validateProtectedState() throws {
        guard !system.isSecureInputEnabled else {
            throw TextInsertionError.secureInputActive
        }
        guard system.isAccessibilityTrusted else {
            throw TextInsertionError.accessibilityPermissionDenied
        }
    }

    private func waitForModifiersRelease() async throws {
        for _ in 0..<Self.releasePollLimit {
            if system.heldModifiers().intersection(Self.watchedModifiers).isEmpty { return }
            try await Task.sleep(for: Self.releasePollInterval)
        }
        throw TextInsertionError.modifiersStillHeld
    }
}
