//! The Rust pipeline must reproduce the shipping macOS pipeline exactly.
//!
//! The fixtures in `core/conformance/fixtures/text/` are not hand-written
//! expectations — they are recordings of what `TextPipeline` in
//! `Packages/DictationCore` actually produced, generated by
//! `core/conformance/generator`. Hand-written expectations only pin down what
//! somebody believed the pipeline did; these pin down what it does.
//!
//! Regenerate them with:
//!
//! ```text
//! swift build --package-path core/conformance/generator
//! ./core/conformance/generator/.build/debug/GenerateFixtures \
//!     core/conformance/corpus-text.json \
//!     core/conformance/fixtures/text/pipeline.json
//! ```
//!
//! A diff in the regenerated fixtures means macOS behaviour changed. That is
//! either a deliberate change — in which case this port changes with it — or a
//! regression the fixtures just caught.

use ramble_text::dictionary::DictionaryReplacement;
use ramble_text::pipeline::{TextPipeline, TrailingCommand};
use serde::Deserialize;

#[derive(Deserialize)]
#[serde(rename_all = "camelCase")]
struct Entry {
    spoken: String,
    written: String,
    inflects: bool,
    allows_phonetic_matching: bool,
}

#[derive(Deserialize)]
#[serde(rename_all = "camelCase")]
struct Span {
    kind: String,
    start: usize,
    end: usize,
    text: String,
}

#[derive(Deserialize)]
#[serde(rename_all = "camelCase")]
struct Fixture {
    name: String,
    dictionary: Vec<Entry>,
    allow_press_return_command: bool,
    phonetic_matching: bool,
    input: String,
    text: String,
    command: Option<String>,
    after_dictionary: String,
    spans: Vec<Span>,
}

fn command_name(command: Option<TrailingCommand>) -> Option<String> {
    command.map(|c| {
        match c {
            // The strings the Swift enum's raw values use.
            TrailingCommand::PressReturn => "pressReturn",
            TrailingCommand::NewLine => "newLine",
        }
        .to_string()
    })
}

fn span_kind_name(kind: ramble_text::SpanKind) -> &'static str {
    use ramble_text::SpanKind::*;
    match kind {
        Backticks => "backticks",
        Path => "path",
        Flag => "flag",
        Identifier => "identifier",
    }
}

#[test]
fn the_rust_pipeline_matches_what_macos_produced() {
    let raw = include_str!("../../conformance/fixtures/text/pipeline.json");
    let fixtures: Vec<Fixture> = serde_json::from_str(raw).expect("fixtures parse");
    assert!(
        fixtures.len() >= 70,
        "the corpus shrank to {} cases — that is a loss of coverage, not a pass",
        fixtures.len()
    );

    let mut failures = Vec::new();

    for fixture in &fixtures {
        let replacements: Vec<DictionaryReplacement> = fixture
            .dictionary
            .iter()
            .map(|entry| DictionaryReplacement {
                id: String::new(),
                spoken: entry.spoken.clone(),
                written: entry.written.clone(),
                inflects: entry.inflects,
                no_acoustic_boost: false,
                allows_phonetic_matching: entry.allows_phonetic_matching,
            })
            .collect();

        let pipeline = TextPipeline {
            replacements,
            allow_press_return_command: fixture.allow_press_return_command,
            phonetic_matching: fixture.phonetic_matching,
        };
        let run = pipeline.run(&fixture.input);

        if run.output.text != fixture.text {
            failures.push(format!(
                "{}: text\n  macOS: {:?}\n  rust:  {:?}",
                fixture.name, fixture.text, run.output.text
            ));
        }
        if command_name(run.output.command) != fixture.command {
            failures.push(format!(
                "{}: command\n  macOS: {:?}\n  rust:  {:?}",
                fixture.name,
                fixture.command,
                command_name(run.output.command)
            ));
        }
        if run.provenance.after_dictionary != fixture.after_dictionary {
            failures.push(format!(
                "{}: afterDictionary\n  macOS: {:?}\n  rust:  {:?}",
                fixture.name, fixture.after_dictionary, run.provenance.after_dictionary
            ));
        }

        let actual_spans: Vec<(String, usize, usize, String)> = run
            .provenance
            .spans
            .iter()
            .map(|s| {
                (
                    span_kind_name(s.kind).to_string(),
                    s.start,
                    s.end,
                    s.text.clone(),
                )
            })
            .collect();
        let expected_spans: Vec<(String, usize, usize, String)> = fixture
            .spans
            .iter()
            .map(|s| (s.kind.clone(), s.start, s.end, s.text.clone()))
            .collect();
        if actual_spans != expected_spans {
            failures.push(format!(
                "{}: spans\n  macOS: {:?}\n  rust:  {:?}",
                fixture.name, expected_spans, actual_spans
            ));
        }
    }

    assert!(
        failures.is_empty(),
        "{} of {} fixtures diverge from macOS:\n\n{}",
        failures.len(),
        fixtures.len(),
        failures.join("\n\n")
    );
}
