import AppKit
import DictationCore
import XCTest

/// Checking the actual entry on the clipboard.
///
/// We work on our named board, and not on the common one: the test is not allowed
/// overwrite what the person copied at that moment.
final class HostOnlyPasteboardTests: XCTestCase {
    private var boardName: String!
    private var board: NSPasteboard!
    private var pasteboard: HostOnlyPasteboard!

    override func setUp() {
        boardName = "is.waiwai.dictation.tests.\(UUID().uuidString)"
        board = NSPasteboard(name: NSPasteboard.Name(boardName))
        pasteboard = HostOnlyPasteboard(name: boardName)
    }

    override func tearDown() {
        board.releaseGlobally()
    }

    func testScenario001() throws {
        _ = try pasteboard.beginHostOnlyWrite("hello from dictation")

        XCTAssertEqual(board.string(forType: .string), "hello from dictation")
    }

    /// Notes for clipboard managers.
    ///
    /// This is the nspasteboard.org agreement: third-party managers do not post with them
    /// entry into your history. Without them, dictated - including passwords, numbers and
    /// everything else that a person dictated settles in someone else’s database forever.
    func testScenario002() throws {
        _ = try pasteboard.beginHostOnlyWrite("secret")

        let types = try XCTUnwrap(board.pasteboardItems?.first?.types)
        XCTAssertTrue(types.contains(HostOnlyPasteboard.transientType), "no TransientType")
        XCTAssertTrue(types.contains(HostOnlyPasteboard.concealedType), "no ConcealedType")
        XCTAssertTrue(types.contains(HostOnlyPasteboard.autoGeneratedType), "no AutoGeneratedType")
    }

    func testScenario003() throws {
        _ = try pasteboard.beginHostOnlyWrite("first")

        XCTAssertNoThrow(try pasteboard.beginHostOnlyWrite("second"))
        XCTAssertEqual(board.string(forType: .string), "second")
    }

    func testScenario004() throws {
        let before = board.changeCount
        _ = try pasteboard.beginHostOnlyWrite("text")

        // The counter is how applications understand that the content is new.
        XCTAssertGreaterThan(board.changeCount, before)
    }

    func testScenario005() throws {
        let generalBefore = NSPasteboard.general.changeCount

        _ = try pasteboard.beginHostOnlyWrite("text")

        XCTAssertEqual(NSPasteboard.general.changeCount, generalBefore)
    }

    func testScenario006() throws {
        board.prepareForNewContents(with: .currentHostOnly)
        let item = NSPasteboardItem()
        item.setString("before dictation", forType: .string)
        XCTAssertTrue(board.writeObjects([item]))

        let transaction = try pasteboard.beginHostOnlyWrite("dictation")
        XCTAssertEqual(board.string(forType: .string), "dictation")
        try pasteboard.restore(transaction)

        XCTAssertEqual(board.string(forType: .string), "before dictation")
    }

    func testScenario007() throws {
        board.prepareForNewContents(with: .currentHostOnly)
        board.setString("before", forType: .string)
        let transaction = try pasteboard.beginHostOnlyWrite("dictation")
        board.prepareForNewContents(with: .currentHostOnly)
        board.setString("new user", forType: .string)

        try pasteboard.restore(transaction)

        XCTAssertEqual(board.string(forType: .string), "new user")
    }

    /// Privacy budget erases the snapshot after two seconds. If by this moment
    /// clipboard is still ours, the previous contents of the person are lost forever -
    /// You cannot remain silent about this, and the dictation should not remain in the buffer.
    func testScenario008() throws {
        board.prepareForNewContents(with: .currentHostOnly)
        board.setString("before dictation", forType: .string)
        let quick = HostOnlyPasteboard(name: boardName, snapshotLifetime: 0.05)
        let transaction = try quick.beginHostOnlyWrite("dictation")

        Thread.sleep(forTimeInterval: 0.3)

        XCTAssertThrowsError(try quick.restore(transaction)) { error in
            XCTAssertEqual(error as? TextInsertionError, .clipboardRestoreFailed)
        }
        XCTAssertNil(
            board.string(forType: .string),
            "Dictated text has no right to be in the clipboard after restore fails"
        )
    }

    /// The same expired snapshot, but the person has already copied his: restore
    /// nothing, you can’t touch someone else’s record, and this is not an error.
    func testScenario009() throws {
        let quick = HostOnlyPasteboard(name: boardName, snapshotLifetime: 0.05)
        let transaction = try quick.beginHostOnlyWrite("dictation")

        Thread.sleep(forTimeInterval: 0.3)
        board.prepareForNewContents(with: .currentHostOnly)
        board.setString("new user", forType: .string)

        XCTAssertNoThrow(try quick.restore(transaction))
        XCTAssertEqual(board.string(forType: .string), "new user")
    }

    /// Copied from a browser or messenger carries its own service types -
    /// this is normal content, not a threat. Snapshot takes any type of data
    /// byte-by-byte and returns them byte-by-byte; failure here would block
    /// dictation after any “copied from Chrome”.
    func testScenario010() throws {
        let custom = NSPasteboard.PasteboardType("org.chromium.source-url")
        board.prepareForNewContents(with: .currentHostOnly)
        let item = NSPasteboardItem()
        item.setString("text from browser", forType: .string)
        item.setData(Data([1, 2, 3]), forType: custom)
        XCTAssertTrue(board.writeObjects([item]))

        let transaction = try pasteboard.beginHostOnlyWrite("dictation")
        XCTAssertEqual(board.string(forType: .string), "dictation")
        try pasteboard.restore(transaction)

        XCTAssertEqual(board.string(forType: .string), "text from browser")
        XCTAssertEqual(board.data(forType: custom), Data([1, 2, 3]))
    }

    /// ConcealedType is metadata, not a reason to block dictation. The previous
    /// clipboard contents are restored after the paste transaction.
    func testScenario011() throws {
        board.prepareForNewContents(with: .currentHostOnly)
        let item = NSPasteboardItem()
        item.setString("hunter2", forType: .string)
        item.setString("", forType: HostOnlyPasteboard.concealedType)
        XCTAssertTrue(board.writeObjects([item]))
        let transaction = try pasteboard.beginHostOnlyWrite("dictation")
        XCTAssertEqual(board.string(forType: .string), "dictation")
        try pasteboard.restore(transaction)
        XCTAssertEqual(board.string(forType: .string), "hunter2")
        XCTAssertTrue(board.types?.contains(HostOnlyPasteboard.concealedType) == true)
    }

    /// A materializable file-promise representation is preserved like any other type.
    func testScenario012() throws {
        let promise = NSPasteboard.PasteboardType("com.apple.pasteboard.promised-file-content-type")
        board.prepareForNewContents(with: .currentHostOnly)
        let item = NSPasteboardItem()
        item.setString("public.png", forType: promise)
        XCTAssertTrue(board.writeObjects([item]))
        let transaction = try pasteboard.beginHostOnlyWrite("dictation")
        try pasteboard.restore(transaction)
        XCTAssertEqual(board.string(forType: promise), "public.png")
    }

    /// Large clipboard values no longer block dictation.
    func testScenario013() throws {
        board.prepareForNewContents(with: .currentHostOnly)
        let item = NSPasteboardItem()
        item.setData(Data(repeating: 0x42, count: 17 * 1024 * 1024), forType: .string)
        XCTAssertTrue(board.writeObjects([item]))
        let transaction = try pasteboard.beginHostOnlyWrite("dictation")
        try pasteboard.restore(transaction)
        XCTAssertEqual(board.data(forType: .string)?.count, 17 * 1024 * 1024)
    }

    func testScenario014() throws {
        board.prepareForNewContents(with: .currentHostOnly)
        board.setString("before dictation", forType: .string)
        let writer = FailFirstPasteboardWriter()
        let failingPasteboard = HostOnlyPasteboard(
            name: boardName,
            writeObjects: writer.write
        )

        XCTAssertThrowsError(try failingPasteboard.beginHostOnlyWrite("dictation")) { error in
            XCTAssertEqual(error as? TextInsertionError, .clipboardWriteFailed)
        }
        XCTAssertEqual(board.string(forType: .string), "before dictation")
    }
}

private final class FailFirstPasteboardWriter: @unchecked Sendable {
    private let lock = NSLock()
    private var callCount = 0

    func write(_ board: NSPasteboard, _ objects: [NSPasteboardWriting]) -> Bool {
        lock.lock()
        callCount += 1
        let shouldFail = callCount == 1
        lock.unlock()
        return shouldFail ? false : board.writeObjects(objects)
    }
}
