import AppKit
import Carbon.HIToolbox
import DictationCore
import Foundation

// MARK: - Буфер обмена

/// Запись продиктованного в буфер обмена.
public protocol DictationPasteboard: Sendable {
    /// Положить текст так, чтобы он не покинул этот компьютер.
    func writeHostOnly(_ text: String) throws
}

/// Буфер обмена, ограниченный этим компьютером.
///
/// Обычная запись отдаёт содержимое в Universal Clipboard, и продиктованный
/// текст оказывается на всех устройствах Apple ID через iCloud — прямо вопреки
/// обещанию продукта. `prepareForNewContents(with: .currentHostOnly)` это
/// отключает, а пометки просят менеджеры буфера не сохранять запись в историю.
///
/// Голый `clearContents()` здесь запрещён, и это проверяется отдельно —
/// `scripts/check-network-surface.sh`.
public struct HostOnlyPasteboard: DictationPasteboard {
    /// Соглашение сторонних менеджеров буфера обмена: «не сохранять».
    static let transientType = NSPasteboard.PasteboardType("org.nspasteboard.TransientType")
    static let concealedType = NSPasteboard.PasteboardType("org.nspasteboard.ConcealedType")
    static let autoGeneratedType = NSPasteboard.PasteboardType("org.nspasteboard.AutoGeneratedType")

    /// Имя доски. В приложении — общая; в тесте своя, чтобы прогон не затирал
    /// то, что человек в этот момент скопировал.
    private let name: String

    public init(name: String = NSPasteboard.Name.general.rawValue) {
        self.name = name
    }

    public func writeHostOnly(_ text: String) throws {
        let pasteboard = NSPasteboard(name: NSPasteboard.Name(name))
        pasteboard.prepareForNewContents(with: .currentHostOnly)

        let item = NSPasteboardItem()
        item.setString(text, forType: .string)
        item.setString("", forType: Self.transientType)
        item.setString("", forType: Self.concealedType)
        item.setString("", forType: Self.autoGeneratedType)

        guard pasteboard.writeObjects([item]) else {
            throw TextInsertionError.clipboardWriteFailed
        }
    }
}

// MARK: - Края системы

/// Всё, что вставка спрашивает у системы и делает с ней.
///
/// За протоколом — потому что настоящие ответы зависят от того, что человек
/// делает за компьютером прямо сейчас: открыто ли поле пароля, какие клавиши
/// зажаты, живо ли приложение, куда мы целимся.
public protocol InputSystem: Sendable {
    /// Защищённый ввод: поле пароля, терминал с защитой клавиатуры, менеджер
    /// паролей. Туда системой запрещено и посылать события, и читать клавиатуру.
    var isSecureInputEnabled: Bool { get }
    var isAccessibilityTrusted: Bool { get }
    func frontmostApplication() -> TargetApplication?
    /// Какие модификаторы зажаты прямо сейчас.
    func heldModifiers() -> CGEventFlags
    /// Вернуть фокус приложению. `false` — приложения больше нет.
    func activate(_ target: TargetApplication) async -> Bool
    func post(keyCode: CGKeyCode, flags: CGEventFlags) throws
}

public struct SystemInput: InputSystem {
    public init() {}

    public var isSecureInputEnabled: Bool { IsSecureEventInputEnabled() }
    public var isAccessibilityTrusted: Bool { AXIsProcessTrusted() }

    public func frontmostApplication() -> TargetApplication? {
        guard let app = NSWorkspace.shared.frontmostApplication else { return nil }
        return TargetApplication(
            bundleIdentifier: app.bundleIdentifier,
            processIdentifier: app.processIdentifier,
            localizedName: app.localizedName
        )
    }

    public func heldModifiers() -> CGEventFlags {
        CGEventSource.flagsState(.combinedSessionState)
    }

    public func activate(_ target: TargetApplication) async -> Bool {
        guard let app = NSRunningApplication(processIdentifier: target.processIdentifier) else {
            return false
        }
        guard !app.isActive else { return true }

        app.activate()
        // Небольшая пауза: переключение фокуса не мгновенно, а нажатие,
        // отправленное раньше времени, уйдёт не туда.
        try? await Task.sleep(for: .milliseconds(120))
        return true
    }

    public func post(keyCode: CGKeyCode, flags: CGEventFlags) throws {
        guard let source = CGEventSource(stateID: .combinedSessionState),
              let keyDown = CGEvent(keyboardEventSource: source, virtualKey: keyCode, keyDown: true),
              let keyUp = CGEvent(keyboardEventSource: source, virtualKey: keyCode, keyDown: false)
        else {
            throw TextInsertionError.targetUnavailable
        }

        keyDown.flags = flags
        keyUp.flags = flags
        keyDown.post(tap: .cgSessionEventTap)
        keyUp.post(tap: .cgSessionEventTap)
    }
}

// MARK: - Вставка

/// Вставка распознанного текста в активное приложение.
///
/// Работает через буфер обмена и синтетическое нажатие ⌘V: это единственный
/// способ вставить текст в произвольное приложение, не зная его устройства.
public struct TextInserter: TextInserting {
    /// Модификаторы, отпускания которых мы ждём перед ⌘V.
    ///
    /// Иначе ⌘V смешается с удерживаемым модификатором и превратится в чужое
    /// сочетание — например, в Fn+⌘V, которое приложение поймёт совсем иначе.
    ///
    /// Fn обязателен в списке: это горячая клавиша, доступная в настройках, и
    /// без неё ожидание завершалось бы, пока клавишу ещё держат.
    public static let watchedModifiers: CGEventFlags = [
        .maskCommand, .maskControl, .maskAlternate, .maskShift, .maskSecondaryFn,
    ]

    /// Сколько ждать отпускания и с каким шагом.
    static let releasePollLimit = 50
    static let releasePollInterval = Duration.milliseconds(10)

    private let system: any InputSystem
    private let pasteboard: any DictationPasteboard

    public init(
        system: any InputSystem = SystemInput(),
        pasteboard: any DictationPasteboard = HostOnlyPasteboard()
    ) {
        self.system = system
        self.pasteboard = pasteboard
    }

    public func frontmostApplication() -> TargetApplication? {
        system.frontmostApplication()
    }

    public func insert(_ text: String, into target: TargetApplication?) async throws {
        guard !text.isEmpty else { return }

        // Защищённый ввод — не сбой, а нормальная ситуация.
        guard !system.isSecureInputEnabled else {
            throw TextInsertionError.secureInputActive
        }
        guard system.isAccessibilityTrusted else {
            throw TextInsertionError.accessibilityPermissionDenied
        }

        // Фокус возвращаем ДО записи в буфер. Если приложения больше нет, дальше
        // идти нельзя, а буфер к этому моменту ещё не тронут: иначе человек
        // терял бы скопированное там, где вставка всё равно не состоялась.
        try await activate(target)
        try pasteboard.writeHostOnly(text)
        try await waitForModifiersRelease()
        try system.post(keyCode: CGKeyCode(kVK_ANSI_V), flags: .maskCommand)
    }

    public func pressReturn() async throws {
        guard !system.isSecureInputEnabled else {
            throw TextInsertionError.secureInputActive
        }
        guard system.isAccessibilityTrusted else {
            throw TextInsertionError.accessibilityPermissionDenied
        }
        try system.post(keyCode: CGKeyCode(kVK_Return), flags: [])
    }

    /// Вернуть фокус тому приложению, где начиналась диктовка.
    ///
    /// Приложение могли закрыть, пока шло распознавание. Вставлять «куда-нибудь»
    /// в этом случае нельзя: впереди сейчас произвольное окно — вплоть до чужого
    /// поля пароля, — и продиктованное ушло бы туда.
    private func activate(_ target: TargetApplication?) async throws {
        guard let target else { return }
        guard await system.activate(target) else {
            throw TextInsertionError.targetUnavailable
        }
    }

    private func waitForModifiersRelease() async throws {
        for _ in 0..<Self.releasePollLimit {
            if system.heldModifiers().intersection(Self.watchedModifiers).isEmpty { return }
            try await Task.sleep(for: Self.releasePollInterval)
        }
        throw TextInsertionError.modifiersStillHeld
    }
}
