import AppKit
import Carbon.HIToolbox
import DictationCore
import Foundation
import os

/// Вставка распознанного текста в активное приложение.
///
/// Работает через буфер обмена и синтетическое нажатие ⌘V: это единственный
/// способ вставить текст в произвольное приложение, не зная его устройства.
public struct TextInserter: TextInserting {
    private let logger = Logger(subsystem: "is.waiwai.dictation", category: "insert")

    public init() {}

    public func frontmostApplication() -> TargetApplication? {
        guard let app = NSWorkspace.shared.frontmostApplication else { return nil }
        return TargetApplication(
            bundleIdentifier: app.bundleIdentifier,
            processIdentifier: app.processIdentifier,
            localizedName: app.localizedName
        )
    }

    public func insert(_ text: String, into target: TargetApplication?) async throws {
        guard !text.isEmpty else { return }

        // Защищённый ввод — поле пароля, терминал с защитой клавиатуры,
        // менеджер паролей. Туда системой запрещено и посылать события, и
        // читать клавиатуру. Это не сбой, а нормальная ситуация.
        guard !IsSecureEventInputEnabled() else {
            throw TextInsertionError.secureInputActive
        }
        guard AXIsProcessTrusted() else {
            throw TextInsertionError.accessibilityPermissionDenied
        }

        try writeToPasteboard(text)
        await activate(target)
        try await waitForModifiersRelease()
        try postPaste()
    }

    public func pressReturn() async throws {
        guard AXIsProcessTrusted() else {
            throw TextInsertionError.accessibilityPermissionDenied
        }
        try post(keyCode: CGKeyCode(kVK_Return), flags: [])
    }

    // MARK: - Буфер обмена

    /// Положить текст в буфер так, чтобы он не покинул этот компьютер.
    ///
    /// Обычная запись отдаёт содержимое в Universal Clipboard, и продиктованный
    /// текст оказывается на всех устройствах Apple ID через iCloud — прямо
    /// вопреки обещанию продукта. Ограничение хостом это отключает, а пометки
    /// просят менеджеры буфера не сохранять запись в историю.
    private func writeToPasteboard(_ text: String) throws {
        let pasteboard = NSPasteboard.general
        pasteboard.prepareForNewContents(with: .currentHostOnly)

        let items = NSPasteboardItem()
        items.setString(text, forType: .string)
        // Соглашение сторонних менеджеров буфера обмена: «не сохранять».
        items.setString("", forType: NSPasteboard.PasteboardType("org.nspasteboard.TransientType"))
        items.setString("", forType: NSPasteboard.PasteboardType("org.nspasteboard.ConcealedType"))
        items.setString("", forType: NSPasteboard.PasteboardType("org.nspasteboard.AutoGeneratedType"))

        guard pasteboard.writeObjects([items]) else {
            throw TextInsertionError.clipboardWriteFailed
        }
    }

    // MARK: - Фокус

    /// Вернуть фокус тому приложению, где начиналась диктовка.
    private func activate(_ target: TargetApplication?) async {
        guard let target,
              let app = NSRunningApplication(processIdentifier: target.processIdentifier),
              !app.isActive
        else { return }

        app.activate()
        // Небольшая пауза: переключение фокуса не мгновенно, а нажатие,
        // отправленное раньше времени, уйдёт не туда.
        try? await Task.sleep(for: .milliseconds(120))
    }

    // MARK: - Нажатия

    /// Дождаться, пока пользователь отпустит горячую клавишу.
    ///
    /// Иначе ⌘V смешается с удерживаемым модификатором и превратится в чужое
    /// сочетание — например, в Fn+⌘V, которое приложение поймёт совсем иначе.
    private func waitForModifiersRelease() async throws {
        // Fn обязателен в списке: он используется как горячая клавиша по
        // умолчанию, и без него ожидание завершалось бы, пока клавиша зажата.
        let watched: CGEventFlags = [
            .maskCommand, .maskControl, .maskAlternate, .maskShift, .maskSecondaryFn,
        ]

        for _ in 0..<50 {
            let flags = CGEventSource.flagsState(.combinedSessionState)
            if flags.intersection(watched).isEmpty { return }
            try await Task.sleep(for: .milliseconds(10))
        }
        throw TextInsertionError.modifiersStillHeld
    }

    private func postPaste() throws {
        try post(keyCode: CGKeyCode(kVK_ANSI_V), flags: .maskCommand)
    }

    private func post(keyCode: CGKeyCode, flags: CGEventFlags) throws {
        guard let source = CGEventSource(stateID: .combinedSessionState),
              let keyDown = CGEvent(keyboardEventSource: source, virtualKey: keyCode, keyDown: true),
              let keyUp = CGEvent(keyboardEventSource: source, virtualKey: keyCode, keyDown: false)
        else {
            throw TextInsertionError.targetUnavailable
        }

        keyDown.flags = flags
        keyUp.flags = flags
        keyDown.post(tap: .cgSessionEventTap)
        keyUp.post(tap: .cgSessionEventTap)
    }
}
