#!/bin/bash
# The shared recognizer is offline; only explicit model download and Sparkle update may network.
set -euo pipefail
cd "$(dirname "$0")/.."

STATUS=0
violation() { echo "$1" >&2; STATUS=1; }

echo "Checking Rust network call sites..."
ALLOWED='^apps/desktop/src-tauri/src/adapters/download\.rs$'
while IFS= read -r hit; do
  file="${hit%%:*}"
  [[ "$file" =~ $ALLOWED ]] && continue
  violation "Network call outside the model downloader: $hit"
done < <(grep -rnE 'reqwest|ureq|hyper::|std::net|TcpStream|TcpListener|UdpSocket|UnixStream' \
  apps/desktop/src-tauri/src core/*/src --include='*.rs' \
  | grep -vE '^[^:]+:[0-9]+:[[:space:]]*(//|\*)' || true)

echo "Checking shared-core dependency graphs..."
PINNED_CARGO=$(rustup which --toolchain 1.97.1 cargo)
FORBIDDEN='reqwest|hyper|ureq|curl|isahc|attohttpc|surf|awc|tungstenite|quinn|rustls|native-tls|openssl|trust-dns|hickory'
for package in ramble-core ramble-text ramble-model ramble-audio ramble-engine ramble-history; do
  while IFS= read -r dependency; do
    violation "$package unexpectedly depends on networking crate $dependency"
  done < <("$PINNED_CARGO" tree --locked --package "$package" --target all --edges normal --prefix none 2>/dev/null \
    | awk '{print $1}' | sort -u | grep -xE "$FORBIDDEN" || true)
done

echo "Checking update privacy policy..."
INFO="apps/desktop/src-tauri/Info.plist"
plist() { /usr/libexec/PlistBuddy -c "Print :$1" "$INFO" 2>/dev/null || true; }
[[ "$(plist SUEnableAutomaticChecks)" == "true" ]] || violation "Automatic security checks are not explicitly enabled."
[[ "$(plist SUSendProfileInfo)" == "false" ]] || violation "Sparkle system-profile reporting is not disabled."
[[ "$(plist SUAllowsAutomaticUpdates)" == "false" ]] || violation "Unattended update installation is not disabled."

echo "Checking macOS clipboard privacy markers..."
INJECT="apps/desktop/src-tauri/src/adapters/inject.rs"
for marker in CurrentHostOnly org.nspasteboard.TransientType org.nspasteboard.ConcealedType org.nspasteboard.AutoGeneratedType; do
  grep -qF "$marker" "$INJECT" || violation "The macOS paste path is missing $marker."
done

echo "Checking transcript logging..."
if grep -rnE '(println!|eprintln!|log::|tracing::).*(transcript|output\.text|recognized)' \
  apps/desktop/src-tauri/src core/*/src --include='*.rs' \
  | grep -vE ':[0-9]+:[[:space:]]*(//|\*)'; then
  violation "Shipping Rust code logs recognized text."
fi

[[ $STATUS -eq 0 ]] && echo "Network and clipboard privacy surfaces are release-safe."
exit "$STATUS"
